export { default as WebHomepageOffers } from './Web-Homepage-Offers'
export { default as WebHomepageMap } from './Web-Homepage-map'
export { default as WebHomepageStudy } from './Web-Homepage-Study'
export { default as WebHomepageTeam } from './Web-Homepage-Team'
export { default as WebHomepageValues } from './Web-Homepage-Values'
export { default as WebHomepageContact } from './Web-Homepage-Contact'
